export const Questions = [
    {
      prompt: " O que “1” + 2 + 4 retorna em Js ?",
      optionA: "7",
      optionB: "16",
      optionC: "12",
      optionD: "124",
      answer: "D",
    },
    {
      prompt: "Como adicionar um comentário em Js ?",
      optionA: "/* Comentário/*",
      optionB: "<!--Comentário-->",
      optionC: "// Comentário",
      optionD: "/Comment",
      answer: "C",
    },
    {
      prompt: "Como escrever 'HelloWorld' em um alerta ?",
      optionA: "alert('Hello World');",
      optionB: "alertBox('Hello World');",
      optionC: "msgBox('Hello World');",
      optionD: "msg('Hello World');",
      answer: "A",
    },
    {
      prompt: "Como declarar uma variável em Js ?",
      optionA: "v carName;",
      optionB: "var carName;",
      optionC: "variable carName;",
      optionD: "carName = Var",
      answer: "B",
    },
    {
      prompt: "Como abrir nova página no HTML ?",
      optionA: "<a href='url' target='_blank'>",
      optionB: "<a href='url' target='new'>",
      optionC: "<a href='url' new>",
      optionD: "<a href='new' open>",
      answer: "A",
    },
    {
      prompt: "Como fazer uma lista numérica em HTML ?",
      optionA: "<list>",
      optionB: "<dl>",
      optionC: "<ul>",
      optionD: "<ol>",
      answer: "D",
    },
    {
      prompt: "Qual tag Html cria um rodapé na página ?",
      optionA: "<section>",
      optionB: "<div>",
      optionC: "<footer>",
      optionD: "<important>",
      answer: "C",
    },
  ];